### ISSUE TITLE
Add config item to, instead of POSIX flagging, support single dash longform flags only

### ISSUE THREAD

**Issue by p7r0x7** [00JCIV00/cova#24] opened 2023-09-19 01:54 UTC
... instead of having the option to concatenate shortened flags behind a single dash.

This is useful for certain project designs, but not necessary for all, so POSIX is definitely the better default.

I'm currently writing a video encoder and I'm using your project as part of the frontend; if you've used ffmpeg you know why single-dashed longform flags are the way to go.

For clarity, I'm referring to something such as the following:
```sh
$ ffmpeg -i in.mkv -f yuv4mpegpipe - | vpxl -y4m=- -crf=20 -best -tune=butteraugli -ivf=out.ivf
```

Thank you for your consideration.

**Comment by p7r0x7** [comment] 2023-09-19 02:21
I believe this could be implemented by adding two fields to Command.Config: `longform_prefix` and `shorthand_prefix`.

**Comment by 00JCIV00** [comment] 2023-09-19 02:24
Hey! Firstly, glad to see the library is useful for you.

More to your specific issue, I believe that functionality is already at least partially supported. Using the `Option.Config.long_prefix` field, you can specify the long name prefix to simply be `-`, then just set `Option.Config.short_prefix` to nothing (`short_prefix = ''`) and you should be good. That is the intended behavior anyway. If it doesn't work, I'll do some digging and ensure that I fix it.

**Comment by 00JCIV00** [comment] 2023-09-19 02:27
And, in case it isn't clear, the `Option.Config` can be set under `Command.Config.opt_config`, same with `Value.Config` and `Command.Config.val_config`. That way you can set up all of your Argument Types neatly in one go.

Let me know if that all works for you.

**Comment by p7r0x7** [comment] 2023-09-19 02:29
> Hey! Firstly, glad to see the library is useful for you.
> 
> More to your specific issue, I believe that functionality is already at least partially supported. Using the `Option.Config.long_prefix` field, you can specify the long name prefix to simply be `-`, then just set `Option.Config.short_prefix` to nothing (`short_prefix = ''`) and you should be good. That is the intended behavior anyway. If it doesn't work, I'll do some digging and ensure that I fix it.

That's amazing that's exactly what I thought too; guess I didn't read your API well enough!

**Comment by 00JCIV00** [comment] 2023-09-19 02:37
Glad to hear it! No worries on missing that feature. The Docs are still a work in progress, so I'm sure it's not as straightforward as I'd like to understand where everything is located.

I'll wait until you've confirmed that works before closing the issue just in case.

**Comment by p7r0x7** [comment] 2023-09-20 19:39
A null value is not accepted for either of those fields.

**Comment by 00JCIV00** [comment] 2023-09-20 21:22
That's true, and I just realized that `short_prefix = ''` doesn't work. I'll have it fixed in a little bit. Thanks for checking.

**Closed** 2023-09-20 21:49 UTC

**Comment by 00JCIV00** [comment] 2023-09-20 21:51
Try it again when you get a chance. I've made it so both fields are nullable, but only one can be null when making the Option Type. It works in my test app, but I'll definitely re-open the issue if I missed something that doesn't work on your end.

**Comment by 00JCIV00** [comment] 2023-09-20 22:00
Also, the v0.8.0 release has been finalized and merged into main, so this fix is also on the main branch.

**Comment by p7r0x7** [comment] 2023-09-28 23:29
The ',' before each long flag really shouldn't be there when there's only way to use all options, as is the case in my project.

```
USAGE: vpxl [,-mkv "input_path ([]const u8)"] [,-y4m "input_path ([]const u8)"] [,-yuv "input_path ([]const u8)"] [,-webm "output_path ([]const u8)"] [,-ivf "output_path ([]const u8)"] [,-usage "usage_flag (bool)"] [,-help "help_flag (bool)"] | 'usage' 'help' 

HELP:
    COMMAND: vpxl

    DESCRIPTION: a VP9 encoder by Matt R Bonnette

    SUB COMMANDS:
        usage:	Show the 'vpxl' usage display.
        help:	Show the 'vpxl' help display.

    OPTIONS:
        Mkv input:
            [,-mkv "input_path ([]const u8)"]
            
        Y4m input:
            [,-y4m "input_path ([]const u8)"]
            
        Yuv input:
            [,-yuv "input_path ([]const u8)"]
            
        Webm output:
            [,-webm "output_path ([]const u8)"]
            
        Ivf output:
            [,-ivf "output_path ([]const u8)"]
            
        Usage:
            [,-usage "usage_flag (bool)"]
            Show the 'vpxl' usage display.
        Help:
            [,-help "help_flag (bool)"]
            Show the 'vpxl' help display.

```

**Comment by p7r0x7** [comment] 2023-09-28 23:31
@00JCIV00 The ',' before each long flag really shouldn't be there when there's only way to use all options, as is the case in my project.

```
USAGE: vpxl [,-mkv "input_path ([]const u8)"] [,-y4m "input_path ([]const u8)"] [,-yuv "input_path ([]const u8)"] [,-webm "output_path ([]const u8)"] [,-ivf "output_path ([]const u8)"] [,-usage "usage_flag (bool)"] [,-help "help_flag (bool)"] | 'usage' 'help' 

HELP:
    COMMAND: vpxl

    DESCRIPTION: a VP9 encoder by Matt R Bonnette

    SUB COMMANDS:
        usage:	Show the 'vpxl' usage display.
        help:	Show the 'vpxl' help display.

    OPTIONS:
        Mkv input:
            [,-mkv "input_path ([]const u8)"]
            
        Y4m input:
            [,-y4m "input_path ([]const u8)"]
            
        Yuv input:
            [,-yuv "input_path ([]const u8)"]
            
        Webm output:
            [,-webm "output_path ([]const u8)"]
            
        Ivf output:
            [,-ivf "output_path ([]const u8)"]
            
        Usage:
            [,-usage "usage_flag (bool)"]
            Show the 'vpxl' usage display.
        Help:
            [,-help "help_flag (bool)"]
            Show the 'vpxl' help display.

```

**Comment by 00JCIV00** [comment] 2023-09-29 00:00
Agreed. I don't have a way to automatically handle that case right now because of how custom Formats are implemented. However, that same feature is also an easy fix to the problem. If you set the `usage_fmt` field in your Option Config as below, it'll get rid of the comma. 

```zig
// This config will get rid of short options, make long options use `-`, and get rid of the extra `,` in the Usage messages.
.opt_config = .{
    .short_prefix = null,
    .long_prefix = "-",
    .usage_fmt = "[{c}{?c}{s}{?s} \"{s} ({s})\"]",
},
```

These Format fields are available in several other places too, so you can customize the look of your Usage/Help messages to your liking.

**Comment by p7r0x7** [comment] 2023-09-29 00:25
Oh, I was looking for that, thanks for the tip!

**Comment by 00JCIV00** [comment] 2023-09-29 02:13
Any time!
